# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\UAVsInGreenfields\Code\landXML\LandXML_Processor.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LandXMLProcessor(object):
    def setupUi(self, LandXMLProcessor):
        LandXMLProcessor.setObjectName("LandXMLProcessor")
        LandXMLProcessor.resize(569, 880)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        LandXMLProcessor.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(16)
        LandXMLProcessor.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/IntraxIcon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LandXMLProcessor.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(LandXMLProcessor)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 0, 301, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("d:\\UAVsInGreenfields\\Code\\landXML\\intrax.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(LandXMLProcessor)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 90, 520, 748))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radBut_BatchProcess = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.radBut_BatchProcess.setFont(font)
        self.radBut_BatchProcess.setObjectName("radBut_BatchProcess")
        self.verticalLayout_2.addWidget(self.radBut_BatchProcess)
        self.lineEdit_InputTxt = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_InputTxt.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_InputTxt.sizePolicy().hasHeightForWidth())
        self.lineEdit_InputTxt.setSizePolicy(sizePolicy)
        self.lineEdit_InputTxt.setMinimumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_InputTxt.setFont(font)
        self.lineEdit_InputTxt.setObjectName("lineEdit_InputTxt")
        self.verticalLayout_2.addWidget(self.lineEdit_InputTxt)
        self.pBut_BrowseInput = QtWidgets.QPushButton(self.groupBox)
        self.pBut_BrowseInput.setMaximumSize(QtCore.QSize(100, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 240, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.pBut_BrowseInput.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.pBut_BrowseInput.setFont(font)
        self.pBut_BrowseInput.setFlat(False)
        self.pBut_BrowseInput.setObjectName("pBut_BrowseInput")
        self.verticalLayout_2.addWidget(self.pBut_BrowseInput)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_OutputDir = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_OutputDir.setMinimumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_OutputDir.setFont(font)
        self.lineEdit_OutputDir.setObjectName("lineEdit_OutputDir")
        self.verticalLayout_3.addWidget(self.lineEdit_OutputDir)
        self.pBut_BrowseOutput = QtWidgets.QPushButton(self.groupBox_2)
        self.pBut_BrowseOutput.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pBut_BrowseOutput.setFont(font)
        self.pBut_BrowseOutput.setObjectName("pBut_BrowseOutput")
        self.verticalLayout_3.addWidget(self.pBut_BrowseOutput)
        self.radBut_Scims = QtWidgets.QRadioButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radBut_Scims.setFont(font)
        self.radBut_Scims.setObjectName("radBut_Scims")
        self.verticalLayout_3.addWidget(self.radBut_Scims)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.pBut_convertFiles = QtWidgets.QPushButton(self.groupBox_3)
        self.pBut_convertFiles.setObjectName("pBut_convertFiles")
        self.verticalLayout_4.addWidget(self.pBut_convertFiles)
        self.txtEdit_ProgramProgress = QtWidgets.QListWidget(self.groupBox_3)
        self.txtEdit_ProgramProgress.setMinimumSize(QtCore.QSize(500, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txtEdit_ProgramProgress.setPalette(palette)
        self.txtEdit_ProgramProgress.setAutoFillBackground(False)
        self.txtEdit_ProgramProgress.setObjectName("txtEdit_ProgramProgress")
        self.verticalLayout_4.addWidget(self.txtEdit_ProgramProgress)

        self.retranslateUi(LandXMLProcessor)
        QtCore.QMetaObject.connectSlotsByName(LandXMLProcessor)

    def retranslateUi(self, LandXMLProcessor):
        _translate = QtCore.QCoreApplication.translate
        LandXMLProcessor.setWindowTitle(_translate("LandXMLProcessor", "Convert LandXML to MXL"))
        self.groupBox.setTitle(_translate("LandXMLProcessor", "Input"))
        self.radBut_BatchProcess.setToolTip(_translate("LandXMLProcessor", "If selected will convert all *.xml in selected directory to *.mxl"))
        self.radBut_BatchProcess.setText(_translate("LandXMLProcessor", "Batch Process"))
        self.pBut_BrowseInput.setText(_translate("LandXMLProcessor", "Browse"))
        self.groupBox_2.setTitle(_translate("LandXMLProcessor", "Output"))
        self.pBut_BrowseOutput.setText(_translate("LandXMLProcessor", "Browse"))
        self.radBut_Scims.setText(_translate("LandXMLProcessor", "Reference Mark Heights"))
        self.pBut_convertFiles.setText(_translate("LandXMLProcessor", "Convert"))
#import qtResource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LandXMLProcessor = QtWidgets.QWidget()
    ui = Ui_LandXMLProcessor()
    ui.setupUi(LandXMLProcessor)
    LandXMLProcessor.show()
    sys.exit(app.exec_())
